## Contents:
- Tensors
- Operations
- Numpy Bride
- CUDA TENSORS

## Tensors

In [1]:
import torch
import numpy as np

生成为初始化的矩阵

In [2]:
x = torch.empty(5,3)
x

tensor([[3.3837e+16, 4.5673e-41, 4.8136e-35],
        [3.0728e-41, 4.6167e-35, 3.0728e-41],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 4.6396e-35]])

生成随机矩阵

In [3]:
x = torch.rand(5, 3)
x

tensor([[0.3958, 0.4198, 0.8581],
        [0.7631, 0.2119, 0.3941],
        [0.6916, 0.6921, 0.6594],
        [0.8829, 0.9461, 0.9776],
        [0.6213, 0.3436, 0.4100]])

In [4]:
torch.zeros(5, 3, dtype=torch.long)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [5]:
torch.tensor([5.5, 3])

tensor([5.5000, 3.0000])

or create a tensor based on an existing tensor. These methods will reuse properties of the input tensor, e.g. dtype, unless new values are provided by user

In [6]:
x = x.new_ones(4, 4)  
x

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

override dtype, result same size

In [7]:
x = torch.randn_like(x, dtype = torch.float)
x

tensor([[ 0.5133,  1.4327, -0.8785, -1.1418],
        [-1.3450, -1.7778, -0.4797,  0.2584],
        [ 0.5251,  0.2118,  0.1020,  2.2056],
        [-1.1970,  0.3057, -0.2254,  2.2948]])

In [8]:
x.shape

torch.Size([4, 4])

## Operations

In [9]:
y = torch.rand_like(x)
y

tensor([[0.4434, 0.1965, 0.5172, 0.2724],
        [0.9628, 0.6296, 0.8780, 0.1563],
        [0.3343, 0.5503, 0.5874, 0.5402],
        [0.6769, 0.3829, 0.0237, 0.1266]])

In [10]:
y + 3

tensor([[3.4434, 3.1965, 3.5172, 3.2724],
        [3.9628, 3.6296, 3.8780, 3.1563],
        [3.3343, 3.5503, 3.5874, 3.5402],
        [3.6769, 3.3829, 3.0237, 3.1266]])

In [11]:
x + y  # torch.add(x, y)

tensor([[ 0.9567,  1.6292, -0.3613, -0.8694],
        [-0.3823, -1.1482,  0.3984,  0.4147],
        [ 0.8594,  0.7621,  0.6895,  2.7457],
        [-0.5202,  0.6886, -0.2016,  2.4214]])

Addition: providing an output tensor as argument



In [12]:
result = torch.empty_like(x)
torch.add(x, y, out=result)

tensor([[ 0.9567,  1.6292, -0.3613, -0.8694],
        [-0.3823, -1.1482,  0.3984,  0.4147],
        [ 0.8594,  0.7621,  0.6895,  2.7457],
        [-0.5202,  0.6886, -0.2016,  2.4214]])

Addition: in-place



In [13]:
y.add_(x) # adds x to y

tensor([[ 0.9567,  1.6292, -0.3613, -0.8694],
        [-0.3823, -1.1482,  0.3984,  0.4147],
        [ 0.8594,  0.7621,  0.6895,  2.7457],
        [-0.5202,  0.6886, -0.2016,  2.4214]])

Any operation that mutates a tensor in-place is post-fixed with an _. For example: x.copy_(y), x.t_(), will change x.

In [14]:
x[:, -1]  # Just like nump

tensor([-1.1418,  0.2584,  2.2056,  2.2948])

In [15]:
x.reshape(2, -1)  # x.view(2, -1)

tensor([[ 0.5133,  1.4327, -0.8785, -1.1418, -1.3450, -1.7778, -0.4797,  0.2584],
        [ 0.5251,  0.2118,  0.1020,  2.2056, -1.1970,  0.3057, -0.2254,  2.2948]])

In [16]:
x = torch.randn(1)
x.item()

0.008539649657905102

More operations:
http://pytorch.org/docs/torch

## Numpy Bridge
The Torch Tensor and NumPy array will share their underlying memory locations, and changing one will change the other.



In [17]:
a = torch.ones(5)
a

tensor([1., 1., 1., 1., 1.])

In [18]:
b = a.numpy()

In [19]:
a.add_(1)

tensor([2., 2., 2., 2., 2.])

In [20]:
b   #改变tensor，numpy也跟着变了！！

array([2., 2., 2., 2., 2.], dtype=float32)

In [21]:
b = b + 1
b

array([3., 3., 3., 3., 3.], dtype=float32)

In [22]:
a #但是变了numpy，tensor却不会跟着变。并且这个联系会被切断！！详细看下面

tensor([2., 2., 2., 2., 2.])

### Converting NumPy Array to Torch Tensor

- 这样tensor会跟着numpy变

In [23]:
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out = a)
a, b

(array([2., 2., 2., 2., 2.]),
 tensor([2., 2., 2., 2., 2.], dtype=torch.float64))

- 这样不会跟着变

In [24]:
a = np.ones(5)
b = torch.from_numpy(a)
a = a + 1
a, b

(array([2., 2., 2., 2., 2.]),
 tensor([1., 1., 1., 1., 1.], dtype=torch.float64))

- 这样也不会跟着变

In [25]:
a = np.ones(5)
b = torch.from_numpy(a)
a = np.add(a, 1)
a, b

(array([2., 2., 2., 2., 2.]),
 tensor([1., 1., 1., 1., 1.], dtype=torch.float64))

## CUDA TENSORS

- let us run this cell only if CUDA is available
- We will use ``torch.device`` objects to move tensors in and out of GPU

In [28]:
if torch.cuda.is_available():
    device = torch.device('cuda')           # a CUDA device object
    y = torch.ones_like(x, device = device) # 1、directly create a tensor on GPU
    x = x.to(device)                        # 2、or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to('cpu', torch.double))

tensor([1.0085], device='cuda:0')
tensor([1.0085], dtype=torch.float64)
