## TENSOR

In [16]:
import torch

Create a tensor and set requires_grad=True to track computation with it

In [17]:
x = torch.ones(2, 2, requires_grad=True, device='cuda')
x

tensor([[1., 1.],
        [1., 1.]], device='cuda:0', requires_grad=True)

In [18]:
y = x + 2
y

tensor([[3., 3.],
        [3., 3.]], device='cuda:0', grad_fn=<AddBackward>)

In [19]:
y.grad_fn

In [20]:
z = y * y * 3
out = z.mean()
z, out

(tensor([[27., 27.],
         [27., 27.]], device='cuda:0', grad_fn=<MulBackward>),
 tensor(27., device='cuda:0', grad_fn=<MeanBackward1>))

.requires_grad_( ... ) changes an existing Tensor’s requires_grad flag in-place. The input flag defaults to False if not given.

In [21]:
a = torch.randn(2, 2, device='cuda')
a = ((a * 3) / (a - 1))
print(a.requires_grad)
a.requires_grad_(True)
print(a.requires_grad)
b = (a * a).sum()
print(b.grad_fn)

False
True


## GRADIENTS

Let’s backprop now Because out contains a single scalar, out.backward() is equivalent to out.backward(torch.tensor(1)).

In [22]:
out.backward()   #will cause error second time

print gradients d(out)/dx

In [23]:
x.grad

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]], device='cuda:0')

ou should have got a matrix of 4.5. Let’s call the out Tensor “o”. We have that o
https://pytorch.org/tutorials/beginner/blitz/autograd_tutorial.html

In [35]:
x = torch.randn(3, requires_grad=True, device='cuda')
y = x * 2
while y.norm() < 1000:#??????????
    y = y * 2
print(y)

tensor([-615.8381, 1213.6947, -349.6183], device='cuda:0', grad_fn=<MulBackward>)


In [28]:
type(y), type(y.data)  #??????????

(torch.Tensor, torch.Tensor)

In [36]:
gradients = torch.tensor([0.1, 1.0, 0.0001], dtype=torch.float, device='cuda')
y.backward(gradients)    #??????????

x.grad

tensor([ 409.6000, 4096.0000,    0.4096], device='cuda:0')

You can also stop autograd from tracking history on Tensors with .requires_grad``=True by wrapping the code block in ``with torch.no_grad():

In [40]:
print(x.requires_grad)
print((x ** 2).requires_grad)
with torch.no_grad():
    print((x ** 2).requires_grad)

True
True
False


http://pytorch.org/docs/autograd